### ISSUE TITLE
Unrecognized chain ID

### ISSUE THREAD

**Issue by ijourard** [rBurgett/relay-tester#2]
POKT Lint seems to not know how to handle calls to 0047 (OEC). Latency values remain blank after pressing "Run Tests". And this error appears 8 times in browser console:

```
app.tsx:76 Error: relaying.HandleRequest: relaying.NewNodeChecker: ChainFromID: unknown chain 0047
    at rpc-controller.tsx:60:15
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at n (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)
```

**Comment by rBurgett** [comment]
Thank you. We are looking into this now.

**Comment by ijourard** [comment]
Same issue with DFK (03DF) now
